apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  namespace: nagp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: manojrawat1990/api-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
